# Get editor completion based on the config schema
'$schema' = 'https://starship.rs/config-schema.json'

add_newline = false
continuation_prompt = "[❯❯ ](dimmed white)"

format = """($nix_shell$container$fill$git_metrics$cmd_duration\n)\
$character$os$username$directory$git_branch$git_status\n\
🦊 """
right_format = """$all$battery$time"""

[fill]
symbol = ' '

[character]
success_symbol = '[❯❯](green)'
error_symbol = '[❯❯](red)'

[username]
show_always = true
style_root = 'red bold'
style_user = 'purple bold'
format = '[$user]($style) in '

[directory]
read_only = ' 󰌾'

[cmd_duration]
min_time = 0
format = "[ took $duration](italic white)"

# Battery display at different levels
[battery]
format = "[ $percentage $symbol]($style)"
full_symbol = "󰁹"
charging_symbol = "[󰂄](italic bold green)"
discharging_symbol = "󱟞"
unknown_symbol = "󰂑"
empty_symbol = "󱊡"

[[battery.display]]
threshold = 25
style = 'italic bold red'

[[battery.display]]
threshold = 60
style = 'italic dimmed bright-purple'

[[battery.display]]
threshold = 90
style = "italic dimmed bright-green"

[time]
disabled = false
format = "[ $time]($style)"
time_format = "%R"
utc_time_offset = "local"
style = "italic dimmed white"

# [memory_usage]
# symbol = '󰍛 '

# Git informations
[git_branch]
symbol = ' '
style = 'bold red'
truncation_symbol = "⋯"
truncation_length = 11
ignore_branches = ["main", "master"]
only_attached = true

[git_commit]
tag_symbol = '  '
style = 'bold yellow'

[git_metrics]
format = '([▴$added]($added_style))([▿$deleted]($deleted_style))'
added_style = 'italic dimmed green'
deleted_style = 'italic dimmed red'
ignore_submodules = true
disabled = false

[git_status]
stashed = '◆ $count '
conflicted = '✘ '
modified = '[!=](yellow) '
staged = '[++\($count\)](orange) '
deleted = ''
renamed = ''
untracked = '[?](yellow) '
up_to_date = '[√](green)'
ahead = '↑ ${count}'
behind = '↓ ${count}'
diverged = '⇕ ↑ ${ahead_count} ↓ ${behind_count}'
format = "([\\[$all_status$ahead_behind\\]]($style)) "

# Languages/envs
[os]
disabled = false
style = 'bold white'
format = '[$symbol]($style) '

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = "[ ](cyan)"
Artix = " "
CachyOS = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
Nobara = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

[aws]
symbol = "  "

[buf]
symbol = " "

[bun]
symbol = " "

[c]
symbol = " "

[cpp]
symbol = " "

[cmake]
symbol = " "

[conda]
symbol = " "

[crystal]
symbol = " "

[dart]
symbol = " "

[deno]
symbol = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[fennel]
symbol = " "

[fossil_branch]
symbol = " "

[gcloud]
symbol = "  "

[golang]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[hg_branch]
symbol = " "

[hostname]
ssh_symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[kotlin]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
style = 'bold italic dimmed blue'
symbol = " "
format = '[$symbol nix⎪$state⎪]($style) [$name](italic dimmed white)'
impure_msg = '[⌽](bold dimmed red)'
pure_msg = '[⌾](bold dimmed green)'
unknown_msg = '[◌](bold dimmed ellow)'

[nodejs]
symbol = " "

[ocaml]
symbol = " "

[package]
symbol = "󰏗 "

[perl]
symbol = " "

[php]
symbol = " "

[pijul_channel]
symbol = " "

[pixi]
symbol = "󰏗 "

[python]
symbol = " "

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[rust]
symbol = "󱘗 "

[scala]
symbol = " "

[swift]
symbol = " "

[zig]
symbol = " "

[gradle]
symbol = " "
