#
# PRELOADS
#

preload = ~/wallpapers/rose_pine_shape.png


#
# WALLPAPERS
#

wallpaper = , ~/wallpapers/rose_pine_shape.png


#
# SETTINGS
#

ipc = off # Save a little bit of battery life. I'm not using it yet anyway.
