input {
  kb_layout = us,us
  kb_variant = ,intl # us-intl with dead keys
  kb_options = grp:win_space_toggle # change keyboard layout with win+space
  numlock_by_default = true
}

# Laptop integrated keyboard settings
device {
    name = at-translated-set-2-keyboard
    kb_options = caps:swapescape, grp:win_space_toggle # change keyboard layout with win+space
}
