windowrule = float, class:com\.saivert\.pwvucontrol
windowrule = size 60% 70%, class:com\.saivert\.pwvucontrol
windowrule = center 1, class:com\.saivert\.pwvucontrol

windowrule = float, class:Thunar(.*)|nemo(.*)
windowrule = size 50% 50%, class:Thunar(.*)||nemo(.*)

windowrule = workspace special:music, initialTitle:YouTube Music # YTM is a PWA, so its default class is the one of the soft that starts it
windowrule = workspace special:music, class:com.github.th_ch.youtube_music # YTM app

windowrule = float, class:xdg-desktop-portal-gtk
windowrule = size 50% 50%, class:xdg-desktop-portal-gtk

# Steam
# windowrule = rounding 10, title:, class:steam
windowrule = float, title:Friends List, class:steam
windowrule = float, title:Steam (.*), class:steam
windowrule = immediate, class:steam_app_[0-9]+  # Allow tearing for steam games
windowrule = idleinhibit always, class:steam_app_[0-9]+  # Always idle inhibit when playing a steam game
windowrulev2 = workspace empty, class:^steam_app_[0-9]+$ # Always open steam games on a new (empty) workspace
windowrulev2 = fullscreen, class:^steam_app_[0-9]+$ # Always start games in fullscreen mode
