windowrule = float, class:com\.saivert\.pwvucontrol
windowrule = size 60% 70%, class:com\.saivert\.pwvucontrol
windowrule = center 1, class:com\.saivert\.pwvucontrol

windowrule = float, class:Thunar(.*)|nemo(.*)
windowrule = size 50% 50%, class:Thunar(.*)||nemo(.*)

windowrule = workspace special:music, initialTitle:YouTube Music # YTM is a PWA, so its default class is the one of the soft that starts it
windowrule = workspace special:music, class:com.github.th_ch.youtube_music # YTM app

