$customHyprDir = $cConf/custom

source = $customHyprDir/input.conf
source = $customHyprDir/monitors.conf
source = $customHyprDir/rules.conf

exec-once = [workspace 1 silent] foot

# Disable integrated screen on laptop lid close
bindl = , switch:on:Lid Switch,  exec, hyprctl keyword monitor "eDP-1, disable"
bindl = , switch:off:Lid Switch, exec, hyprctl keyword monitor "eDP-1, 1920x1080@60, 0x0, 1"

bind = SUPER, F1, exec, $customHyprDir/scripts/fast-mode.sh

bind = SUPER+ALT, K, sendshortcut, ALT, K class:^(discord)$

# bind = Super, left, movefocus, l
# bind = Super, right, movefocus, r
# bind = Super, up, movefocus, u
# bind = Super, down, movefocus, d

bind = Super+Shift, H, movewindow, l
bind = Super+Shift, L, movewindow, r
bind = Super+Shift, K, movewindow, u
bind = Super+Shift, J, movewindow, d

