# Laptop integrated keyboard settings
device {
    name = at-translated-set-2-keyboard
    kb_options = caps:swapescape
}

# Laptop integrated monitor
monitor = eDP-1, 1920x1080@60, 0x0, 1
monitor = HDMI-A-1, highres@highrr, auto-right, auto
# monitor=eDP-1,disable,HDMI-A-1 # disables eDP-1 when HDMI is present

# Disable integrated screen on laptop lid close
bindl = , switch:on:Lid Switch,  exec, hyprctl keyword monitor "eDP-1, disable"
bindl = , switch:off:Lid Switch, exec, hyprctl keyword monitor "eDP-1, highres@60, 0x0, 1"

bind = SUPER, F1, exec, ~/.config/hypr/scripts/fast-mode.sh
